telekom/scale

package.json
This feature should enhance the development flow. After `yarn` the `build` command is executed automatically, so the dependent `packages` have their artefacts and are ready to start
=> automatically run build after install

package.json, packages/components-react/jest.config.js, packages/components-react/package.json, packages/components-react/src/alert.test.tsx, packages/components-react/src/alert.tsx, packages/components-react/src/button.test.tsx, packages/components-react/src/button.tsx, packages/components-react/src/card.test.tsx, packages/components-react/test/setup-tests.ts, packages/components-react/tsconfig.json, packages/config/jest.config.js, packages/config/package.json, packages/config/tsconfig.json, packages/tsconfig.json, test/__mocks__/fileMock.js, test/__mocks__/styleMock.js, yarn.lock
This PR introduces the initial draft of the `jest` test setup. 
Currently this covers `components-react` but will be applied to most of the other packages as well. 
The root `jest.config` is coming from the shared `@telements/config` package
Some configuration (like mocks) is currently placed in the `monorepo` top directory under `test` but  may be soon ported into `@telements/config` as well
To run the test suite - run `yarn` in the root dir, then navigate to `packages/components-react` and run `yarn test`. 
> Note: For demonstration purposes the current tests are kept very simple and will be improved as the library becomes more mature 
If all goes well, you should see something similar to this in your terminal:
=> add `jest` test setup for `components-react`

packages/components/src/components/alert/readme.md, packages/components/src/components/card/readme.md, packages/components/src/components/input-text/readme.md
Run `yarn build` to generate missing docs by stencil.js
=> fix: auto generate docs for existing components

packages/generator-sketch/src/index.js, packages/generator-sketch/src/inject.js, packages/html-to-sketch/html2asketch/helpers/utils.ts, packages/html-to-sketch/html2asketch/model/textAttributedString.ts, packages/html-to-sketch/html2asketch/nodeToSketchLayers.ts, packages/html-to-sketch/html2asketch/nodeTreeToSketchGroup.ts, packages/html-to-sketch/package.json
Tracking work on completing symbol instances support.
* Creates an overrideValue for each value that differs between the SymbolMaster and the symbol instance JSON from html2sketch.
=> Symbol instances

packages/components/src/utils/css-in-js.tsx
this PR refactors `CssInJs`'s `componentWillUpdate` hook to avoid appending new `style` elements to the DOM whenever a component's `styles` property changes. Instead it injects a single style sheet and modifies that upon changes.
=> perf: update old sheet with new component rules

packages/generator-sketch/src/index.js, packages/generator-sketch/src/inject.js, packages/html-to-sketch/html2asketch/nodeToSketchLayers.ts
New rebased branch.
This PR tracks work to add image support to sketch-generator.
Now images are saved to disk from puppeteer using an `on('response')` handler. The saved images are added to the generated Sketch file by creating a new sketch-constructor Bitmap of the image during `yarn sketch`, and updating the generated `image` object to have the same `_ref`. 
This is currently tested with same-origin & non-same-origin PNG and JPEG images in `img`, CSS `background-image: url()`, with dataURLs and in `:after`/`:before` `content: url()`.
The pseudo-element content image support also adds more complete parsing of the content string, with preliminary support for `attr()` and [CSS &lt;image>](https://developer.mozilla.org/en-US/docs/Web/CSS/image) properties (gradients, etc.) There's also an …
=> Feature/images - add images to generated Sketch files

README.md
please esp. check the "neutral" examples as the original did not have "neutral". text from here: https://github.com/telekom/scale-republish-prep
=> typos + -neutral snippets

packages/components/src/components/button/button.css, packages/components/src/components/button/button.tsx, packages/storybook-vue/stories/3_components/button/Button.stories.mdx
the "click event fired when disabled" issue is not reproducible in Storybook, and I'm 99% sure that's because of the "Vue layer" — I think we should consider —proudly— switching to a WC-only Storybook
=> fix: button

packages/components/package.json
=> chore: update and tidy up stencil npm scripts

packages/components/src/components/dropdown/dropdown.css
fixes additional spacing for selected input value generated by firefox
=> fix(select): add  -moz query for rendering visual padding correctly

packages/storybook-vue/stories/2_for_developers/03.ScaleAndAngular_de.md, packages/storybook-vue/stories/2_for_developers/03.ScaleAndAngular_en.md
Hello,
I tried to implement Scale in an empty Angular project, but the styles were not applied correctly (missing fonts and colors). After some research, I found out that the stylesheet in ``angular.json`` was missing. After I added the specified line, all styles were applied correctly and worked. 
I think this should be added in the storybook to avoid any surprises.
=> docs(storybook): added angular.json

README.md, packages/components/README.md, packages/design-tokens/README.md, packages/storybook-vue/stories/2_for_developers/01.Setup_de.md, packages/storybook-vue/stories/2_for_developers/01.Setup_en.md
The vanilla snippets currently use a broken URL, this fixes that.
=> fix(components): incorrect esm module link in README

packages/design-tokens/scripts/build.js, packages/design-tokens/src/tokens.js
These are some docs that lived in the README. They got deleted in the GitHub transition. I think they could be useful in the future.
=> docs(design-tokens): restore some docs internally

packages/storybook-vue/stories/3_components/table/Table.stories.mdx
Hi,
while working with Tables I noticed a discrepancy between the storybook documentation and the presented examples.
The examples are using `<caption>` Tags following the HTML standard. But the corresponding shown code is using h5 Tags.
I concluded that `<h5>` is probably leftover from previous Versions. So I adjusted the Markdown. Also, I added a Comment suggesting to shift out the caption so it doesn't get shown (the same way it's done in the Example).
I did a little bit of digging into the old GitLab repo but couldn't pin down the exact Point h5 got introduced. But I concluded that `<caption>` should be mentioned here since WCAG 2.0 ([WCAG Table Caption](https://www.w3.org/WAI/tutorials/tables/caption-summary/))  implies the usage for accessibility reasons.
The storybook `build` and …
=> chore: change h5 in Tables to caption (same as code example)

packages/storybook-vue/stories/3_components/progress-bar/ProgressBar.stories.mdx, packages/storybook-vue/stories/3_components/progress-bar/ScaleProgressBar.vue
Hi,
while working with the progress bar I noticed another problem with the documentation. It suggests that show-status has a default value, which is not the case in the Stencil Component. Also, the shown Code for the first and second examples doesn't match the canvas.
I changed the default Value of show-status to none in the Storybook-Vue file so it does not suggest that show-status has a default.
Also, I changed the first example to be coherent to before adding `show-status: true` to the canvas and adding it to the example HTML code.
The second example now does not show the status anymore, but the example HTML code also doesn't contain it.
Like this, the Storybook represents the Stencil component and the example codes match the canvases they represent.
The Storybook is building and is …
=> chore: adjust documentation showStatus no default

packages/components/src/html/index.html
Tries to fix the problem I found with #382 
Uses the same example code as the Storybook.
=> fix: icon Buttons on Indexhtml wrong syntax

packages/components/src/components/button/__snapshots__/button.spec.ts.snap, packages/components/src/components/button/button.spec.ts, packages/components/src/components/button/button.tsx
child nodes, which are whitespace strings have to be removed to let 'icon after' work fine
=> fix: remove child nodes, which are whitespace strings

packages/components/scripts/icon-component.hbs, packages/storybook-vue/stories/3_components/icon/Icon.stories.mdx, packages/storybook-vue/stories/3_components/icon/ScaleIconLibraryExample.vue
Hi ✌️
yesterday I opened #405 
Resulting from that I took a look at what the icon handlebar actually does (icon-component.hbs). And as you can see in line 44 of the icon component, it just adds the `color` Prop as an SVG `fill` attribute.
This is the same behavior the scale-icon Wrapper Component has (over the pathAttributes).
So I added a `fill` prop which has priority over the `color` prop. Resulting in this behavior:
```
<scale-icon-action-circle-close color="green"> </scale-icon-action-circle-close>
<scale-icon-action-close fill="red"> </scale-icon-action-close>
<scale-icon-action-download fill="red" color="green"> </scale-icon-action-download>
```
I reorded the Storybook a bit so it meets the behavior. Showing examples with `fill` instead of `color`.
Like this scale-icons and icons …
=> feat: add fill to icon with higher priority than color

packages/components-sketch/views/index.hbs, packages/components-sketch/views/tooltip.hbs, packages/components/src/components/tooltip/readme.md, packages/components/src/components/tooltip/tooltip.css, packages/components/src/components/tooltip/tooltip.tsx, packages/storybook-vue/.storybook/usage-addon/usage.js, packages/storybook-vue/stories/3_components/tooltip/ScaleTooltip.vue, packages/storybook-vue/stories/3_components/tooltip/Tooltip.stories.mdx, packages/storybook-vue/stories/3_components/tooltip/tooltip.md, packages/storybook-vue/stories/3_components/tooltip/tooltip_de.md
Hey @marvinLaubenstein ✌️,
we talked last week about the tooltips.
I finally had some time to add my Ideas to the Tooltips. For now, it's mostly documentation and two fixes.
1. Changed default font-size design Token to `--scl-font-size-16` matching the Sketch File in your Design Repo.
2. Added the `--scl-z-index-70` Designtoken. The internal CCS Var was already used but without a Value. I also changed the name to match the naming scheme.
- Added descriptions to the Props
- Added Handlebars -> Generating Sketch Components
The Sketch hierarchy looks like this:
But I'm having an issue with the `::after` arrow of the Element being rendered as a block border instead of an arrow Style. Also, the Sketch Box is way bigger than the Sketch Element. Maybe I could use some assistance here on how to …
=> chore: documentation and z-index

packages/components/src/components/radio-button/radio-button.tsx, packages/components/src/components/radio-button/readme.md, packages/components/src/html/radio.html
With the current radio button implementation, the `scaleChange` event is being fired only once. This makes it impossible to hook with framework's state/models.
This PR fixes that.
(It also fixes the `click` event being fired twice while clicking on the label.)
`input[type="radio"]` elements only fire `change` events after user input and only when being actually `checked`, not unchecked (there is no `change` event while being unchecked). Since our component relies on this `change` event to update its `checked` property, this remains `true` forever after the first `change` event. And, since the `scaleChange` event gets fired using a watcher on this same `checked` prop, it fires only once: the one time `checked` changes from `false` to `true`.
---
Some inspiration: …
=> fix: events and `checked` prop in Radio

packages/components/src/components/tag/readme.md, packages/components/src/components/tag/tag.tsx, packages/storybook-vue/stories/3_components/tag/Tag.stories.mdx
Hey,
I noticed in the Storybook that the Chip/Tags don't have a selector for `variant` and `size` like for example Buttons.
For Buttons it looks like this:
vs
for Tags
Also, I noticed that size and variant is per default not specified and has no enumerating type like Buttons have.
Button.tsx Line 25:
`@Prop() size?: 'small' | 'large' = 'large';`
vs Tag.tsx Line 21:
`@Prop() size?: string = '';`
So I changed that and also added a select field to the Storybook. Now it looks like this:
I'm thinking of defining the `default` variant/size (or primary) in the component too. It would not be a breaking change but would improve maintainability in my view.
Let me know if this should be added to this PR.
=> chore: add better doc for variant and size to Tags

packages/components/src/components/date-picker/date-picker.tsx
Hi 🧑‍💻
This is a simple fix for: #440 
Added a watcher to the Value for outside changes of `value`. 
Since the `hasValue` State doesn't seem to have reactivity on its own.
I'm not absolutely keen if StencilJS has some way to make States reactive directly, if there is a possibility to handle it directly in the State that might be nicer. But I couldn't find such functionality.
Can be tested like this:
```
<scale-date-picker label="Helper Text" id="Test" value=""></scale-date-picker>
<script>
setTimeout(()=>{
document.getElementById('Test').setAttribute("value", "2020-12-31")
}, 6000)
</script>
```
This also enables Stuff like this:
```
setTimeout(()=>{
document.getElementById('Test').setAttribute("value", "2020-12-31")
}, 6000)
setTimeout(()=>{ …
```
=> fix: datepicker not updating on outside value change

packages/components/src/components/tag/readme.md, packages/components/src/components/tag/tag.css, packages/components/src/components/tag/tag.tsx, packages/storybook-vue/stories/3_components/tag/ScaleTag.vue, packages/storybook-vue/stories/3_components/tag/Tag.stories.mdx
=> fix(tag): keyboard support for dismiss button

packages/components/src/components/telekom/app-shell/app-shell.css
Set main content flex value to 1.
=> fix: add flex value to main content

packages/components/src/components/checkbox/checkbox.css
The CSS Variable `--spacing-control` on the Checkbox is never applied instead it directly applies a design token variable.
I think this was the intended way the variable should work.
=> fix: spacing control is never applied on checkbox

packages/components/src/components/tag/tag.css, packages/components/src/components/telekom/app-footer/app-footer.css, packages/components/src/components/telekom/app-header/app-header.css, packages/components/src/components/telekom/app-mega-menu/app-mega-menu.css, packages/components/src/components/telekom/app-navigation-main-mobile/app-navigation-main-mobile.css, packages/components/src/components/telekom/app-navigation-user-menu/app-navigation-user-menu.css, packages/components/src/components/telekom/app-shell/app-shell.css, packages/components/src/components/telekom/nav-icon/nav-icon.css, packages/components/src/components/telekom/nav-segment/nav-segment.css, packages/components/src/components/text-field/text-field.css, packages/components/src/components/textarea/textarea.css, packages/components/src/components/toggle-button/toggle-button.css, packages/components/src/components/toggle-group/toggle-group.css, packages/components/src/components/tooltip/tooltip.css
I have noticed there are some files which still have wrong spacing tokens (`--telekom-spacing-unit-x*`). So I update them. Also I update the name of `--telekom-color-ui-regular`  as well. But ONLY in those componenets I am working on. I did not update other component in order not to create merge conflict.
=> refactor: remove token spacing dash, rename ui token from normal to regular

packages/components/src/components/checkbox/checkbox.tsx
Fixes #817 
(Emitting `scaleChange` when `disabled` changes doesn't make much sense. I guess it was there to support the Checkbox Group?)
=> fix(checkbox): do not emit change from watching `disabled`

packages/components/src/components/tooltip/tooltip.css
The css Variable of the Tooltips adding the z-index is never applied. This leads to behavior described in #818
This fixes this applying it to `tooltip-positioner`.
Can be tested by applying this to the index.html:
```
<scale-tooltip
content="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lore"
title="Some"
>
<scale-icon-alert-information size="18" />
</scale-tooltip>
<scale-text-field
size="small"
label="Textfield"
name="Name"
id="FieldID"
value="some"
/>
```
=> fix(tooltip): add z-index

packages/components/src/components/modal/modal.tsx
I have removed the title attribute because we already have `aria-label` attribute.
=> fix: remove title attribute from modal window

packages/components/src/components/telekom/app-header/app-header.tsx
This fixes issue app-logo in navbar is not focusable when header is sticky
=> fix: app-logo not focusable when header is sticky

packages/components/src/components/checkbox/checkbox.css, packages/components/src/components/data-grid/data-grid.css
I tried to use the -moz- prefix but that didn't fix the issue. Removing the property completely solves it
checked the history looks like the property was added to fix some pagination problem, but pagination seems fine even without it @marvinLaubenstein maybe you remember https://github.com/telekom/scale/commit/3507aa24d37bcdf6c2ea5781e5669c517e358072 ?
=> fix: windows firefox problem with fit-content

packages/components/src/components/switch/__snapshots__/switch.spec.ts.snap, packages/components/src/components/switch/switch.tsx
fix #822 
✅ Cross-checked with different accessibility tested switches with same structure (input [type=checkbox])
✅ Voice Over output checked
👉 Thus I would like to merge the accessibility change wish, since it brings in any case an improvement. 
@nowseemee can you please approve this 🙂
=> fix: Potential a11y issue with switch #822

examples/nuxt3-boilerplate/package.json
The boilerplate at the moment only works by yarn linking the scale-components using the latest stencil version. Updating its scale-components version to the next release version so that the example will actually work "out of the box"
=> fix: use next release version for working nuxt3 app

packages/components/src/components/button/button.e2e.ts, packages/components/src/components/button/button.tsx
Fixes #859.
- Not a "React wrapper" thing
- Same problem with "generic" web component
- Forms with a single text input will be submitted with the Enter key, even without a button: https://stackoverflow.com/a/35235768
---
=> feat(button): forms will submit with Enter key

packages/components/stencil.config.ts
In our Project we have problems to use the Telekom-Scale-Components with vite and get allways Console.Problems with a blank page:
> TypeError: Failed to fetch dynamically imported module: http://localhost:3000/node_modules/.vite/deps/scale-radio-button-group.entry.js?import undefined
> TypeError: Failed to fetch dynamically imported module: http://localhost:3000/node_modules/.vite/deps/scale-button.entry.js?import undefined
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isProxied')
at initializeComponent (@telekom_scale-components_loader.js?v=6b475f15:2739:17)
---
For this type of problems Stencil have a extra flag named "[experimentalImportInjection](https://stenciljs.com/docs/config-extras#experimentalimportinjection)". 
Setting this …
=> Add vite-support for the package scale-components

packages/components/package.json, packages/components/src/global/scale.ts, yarn.lock
- Safari is no longer an issue, and [browser support is pretty great imo](https://caniuse.com/web-animation)
- `web-animations-js` is almost [15 kB gzipped](https://bundlephobia.com/package/web-animations-js@2.3.2) 🫣
- we're currently only using the Web Animations API in the Modal, and [it's implemented in a "progressive-enhancement" way](https://github.com/telekom/scale/blob/fdf09ccba8ce9a533ba7b8a1c31174a9f7bc377b/packages/components/src/components/modal/modal.tsx#L209-L224) (it won't animate but it'll open/close normally if the API is not supported)
@nowseemee 👀 🙏
=> chore: remove `web-animations-js` dep

packages/components/src/components/progress-bar/__snapshots__/progress-bar.spec.ts.snap, packages/components/src/components/progress-bar/progress-bar.spec.ts, packages/components/src/components/progress-bar/progress-bar.tsx, packages/components/src/components/progress-bar/readme.md
Property 'percentage_start' at component `<scale-progress-bar>`
We are working on a Telekom-internal project. We just startet an new UI application for the TROPOS team, using this really great component library.
We have a web page displaying a multi-step, partly-manual/partly-automated processing status. Our UI will keep polliing this page to reflect any server-side status changes. In this scenario it's quite annoying that the progress bar would alway restart it's animation from scratch.<br/>
Instead, we would rather set the previous percentage and thus only have nice animations on actual status changes.
=> feat: component ProgressBar -  add optional input property 'percentage_start'

packages/components/src/components/slider/__snapshots__/slider.spec.ts.snap, packages/components/src/components/slider/readme.md, packages/components/src/components/slider/slider.css, packages/components/src/components/slider/slider.spec.ts, packages/components/src/components/slider/slider.tsx, packages/components/src/html/slider.html, packages/storybook-vue/stories/components/slider/ScaleSlider.vue, packages/storybook-vue/stories/components/slider/Slider.stories.mdx
=> refactor(slider): mobile 📱 

packages/components/README.md, packages/components/package.json, packages/components/stencil.config.ts, packages/storybook-vue/stories/setup_and_info/GettingStartedForDevelopers_de.md, packages/storybook-vue/stories/setup_and_info/GettingStartedForDevelopers_en.md
…with the new [`dist-custom-elements`](https://stenciljs.com/docs/custom-elements#distributing-custom-elements).
This dist allows bypassing Stencil's lazy loading, and import only a specific set of components programatically (no magic), e.g.
```js
import { defineCustomElementScaleButton } from '@telekom/scale-components'
defineCustomElementScaleButton() // only `<scale-button>` is loaded
```
See https://github.com/telekom/scale/issues/1167
=> chore: replace deprecated `dist-custom-elements-bundle` dist

packages/components/src/components/menu-flyout-item/menu-flyout-item.tsx, packages/components/src/components/menu-flyout-item/readme.md, packages/components/src/components/menu-flyout-list/menu-flyout-list.tsx
Related to https://github.com/telekom/scale/issues/915#issuecomment-1310460002
> We can include the original click event that has ctrlKey inside the details of the emitted scale-select event. That should be an easy fix. We could name it originalEvent (in a jQuery fashion).
@felix-ico could you please review this one 🙏
=> feat(menu-flyout): pass `originalEvent` in `scale-select` event

packages/components/src/components/dropdown-select/dropdown-select.tsx, packages/components/src/components/dropdown-select/readme.md, packages/components/src/html/dropdown-select.html
Fixes #1360.
This is exclusively only adding the prop to `<scale-dropdown-select>`. So when you listen for the `scale-change` event you can use `event.target.name`.
@filipjnc I think a hidden input element would be best added by yourself as a sibling of the Dropdown Select. If we put it inside the shadow DOM it will have no effect on form submission.
In the near future we could use [`ElementInternals`](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals) to make ["form associated" components](https://web.dev/more-capable-form-controls/). It's currently not supported by Safari, thou there's [a polyfill](https://www.npmjs.com/package/element-internals-polyfill). A there's also [other ways to do it](https://github.com/shoelace-style/shoelace/blob/next/src/internal/form.ts). …
=> feat(dropdown-select): add `name` prop

packages/components/src/components/telekom/app-footer/app-footer.tsx, packages/components/src/components/telekom/app-navigation-user-menu/app-navigation-user-menu.tsx
Hi there, we're using scale in one of the web applications at TelekomCLOUD marketplace and missing a feature to set the target of the links in the header and footer to `_blank`. 
Unfortunately we were unable to test the framework as the build process always failed at certain points, but I hope it works this way.
=> feat: add link target variables to menu and footer

packages/components/src/components/dropdown-select/dropdown-select.tsx, packages/components/src/components/segmented-button/segmented-button.tsx
Like mentonied in an issue before, the vue-router package make some problems with Scale (#1194).
In our project we have found two new problems:
1. The DropdownSelect have no value set, when setting some default.
2. The SegmentedButton ist not selected it default inside ScaleModal (#1580).
For the first point I have two Sandboxes, one with using vue-router and one without it.
[Sandbox 1: DropdownSelect with using vue-router](https://stackblitz.com/edit/vitejs-vite-dlcfr4?file=src%2FApp.vue)
[Sandbox 1: DropdownSelect without vue-router](https://stackblitz.com/edit/vitejs-vite-atvrmi?file=src%2FApp.vue)
For the second point, there is one Sandbox in my linked issue (#1580).
The behaviour is by both the same. It looks like the vue-router package don't allow using the method `getAttribute()` …
=> fix: no value is set in DropdownSelect and SegmentedButton when using vue-router

packages/components/src/components/dropdown/dropdown.css
This fixes an issue where the dropdown still had the dark background on hover even though the app is in lightmode. It occured when the prefered color scheme was set to dark but the app set to light-mode using the `data-mode` attribute.
The issue is fixed by overwriting the styles for this case.
=> fix: dropdown still has dark background on hover when the app is in lightmode

packages/components/src/components/tab-header/readme.md, packages/components/src/components/tab-header/tab-header.tsx, packages/components/src/components/tab-nav/__snapshots__/tab-nav.spec.ts.snap, packages/components/src/components/tab-nav/readme.md, packages/components/src/components/tab-nav/tab-nav.spec.ts, packages/components/src/components/tab-nav/tab-nav.tsx
Should fix #1372 for good 🙏 
Removes the need for the recently-added `autoFocus` prop. (I'm intentionally not deprecating it.)
Please @felix-ico take a look after CI is all green.
=> fix(tab-header): focus problems (#1372)

packages/components/src/components/loading-spinner/loading-spinner.css
center the loading icon (in align with text)
=> fix(loading-spinner): center the loading icon in align with text

packages/components/src/components/telekom/telekom-footer-extended-navigation/telekom-footer-extended-navigation.css
=> fix(telekom-footer-extended-navigation): css fixes

packages/components/src/components/dropdown-select/dropdown-select.css, packages/components/src/components/dropdown-select/dropdown-select.tsx, packages/components/src/components/dropdown-select/readme.md
added a span as discussed
HCM 
DISABLED
These issues I could not reproduce, there is some label for a disabled dropdown-select referenced in the feedback we got but i could not see it in storybook or anywhere in the code
=> fix: a11y feedback

packages/components/src/components/radio-button/radio-button.css, packages/storybook-vue/stories/components/radio-button-group/RadioButtonGroup.stories.mdx
Alternative fix for #2069 — the main difference is avoiding chaning the markup because of accessibility (for extra safety): we cannot easily repeat all the extensive testing the component went through to get the AA.
=> fix(radio-button): emit change event when clicking input-label gap

packages/components/src/components/radio-button/radio-button.css, packages/components/src/components/radio-button/radio-button.tsx
I removed the `click` handler because it wasn't really needed since the logic was duplicated.
@felix-ico do you see it the same way?
Regarding CSS, `hover` and `active` now target the actual control to avoid triggering them with clicks that trigger no change event… (I hope that makes sense)
=> fix(radio-button): polish click handling, hover, etc

packages/components/src/components/telekom/telekom-header/telekom-header.tsx
fix for https://github.com/telekom/scale/issues/2130
=> fix: set scrolled attribute only when offset is larger than the header

packages/components/src/components/telekom/logo/logo.tsx, packages/components/src/components/telekom/telekom-footer/readme.md, packages/components/src/components/telekom/telekom-footer/telekom-footer-content.tsx, packages/storybook-vue/stories/components/telekom-footer/FooterContent.vue, packages/storybook-vue/stories/components/telekom-footer/TelekomFooter.stories.mdx
fixes https://github.com/telekom/scale/issues/2119
allow setting footer logo link and title. 
@acstll I'm not really sure how to document these props in storybook though, as they are technically for the child component `telekom-footer-content`, which doesn't have its own storybook page.  Do you have any ideas on that?
=> fix: allow setting href on footer logo

packages/components/src/components/checkbox-group/checkbox-group.spec.ts, packages/components/src/components/checkbox-group/checkbox-group.tsx, packages/components/stencil.config.ts, packages/components/test-setup.ts
fixes https://github.com/telekom/scale/issues/1774
=> fix: update parent checkbox state when new children are added dynamically

packages/components/src/components/checkbox/checkbox.tsx, packages/components/src/components/dropdown/dropdown.tsx, packages/components/src/components/input/__snapshots__/input.spec.ts.snap, packages/components/src/components/input/input.tsx, packages/components/src/components/radio-button/radio-button.tsx, packages/components/src/components/text-field/text-field.tsx, packages/components/src/components/textarea/__snapshots__/textarea.spec.ts.snap, packages/components/src/components/textarea/textarea.tsx
fixes https://github.com/telekom/scale/issues/2165
=> fix: set aria-invalid true when invalid

package.json
Hopefully saving contributors some time. Using node greater than 16 or not using yarn v1 yields a bunch of install/build errors.
=> feat: add engines to package.json

packages/components/package.json, packages/components/src/components/data-grid/cell-handlers/cell-interface.ts, packages/components/src/components/data-grid/cell-handlers/date-cell.tsx, packages/components/src/components/data-grid/data-grid.tsx, packages/storybook-vue/stories/components/data-grid/DataGrid.stories.mdx, yarn.lock
this fixes a supportpal issue (56456) - sorting by german date format in data grid date cell
=> fix: allow sorting by german date format

packages/components/src/components/checkbox/__snapshots__/checkbox.spec.ts.snap, packages/components/src/components/checkbox/checkbox.tsx, packages/components/src/components/radio-button/radio-button.tsx, packages/components/src/components/switch/__snapshots__/switch.spec.ts.snap, packages/components/src/components/switch/switch.css, packages/components/src/components/switch/switch.tsx
fix https://github.com/telekom/scale/issues/2214
=> fix: use spans inside labels for correct html

packages/components/src/components/tab-panel/readme.md, packages/components/src/components/tab-panel/tab-panel.tsx, packages/storybook-vue/stories/components/tab-navigation/TabNav.stories.mdx, packages/storybook-vue/stories/components/tab-navigation/TabPanel.vue
https://github.com/telekom/scale/issues/2209
=> fix: add prop for removing tabindex

packages/components/src/components/dropdown-select/dropdown-select.tsx, packages/components/src/components/dropdown-select/readme.md
this should fix https://github.com/telekom/scale/issues/2173
=> fix: add hidden input with name attribute

packages/components/src/components/telekom/logo/logo.tsx, packages/components/src/components/telekom/telekom-footer/readme.md, packages/components/src/components/telekom/telekom-footer/telekom-footer-content.tsx, packages/components/src/components/telekom/telekom-header/telekom-header.tsx, packages/storybook-vue/stories/components/telekom-footer/FooterContent.vue
fixes https://github.com/telekom/scale/issues/2188
=> fix: logo only focusable if href provided

packages/components/src/components/telekom/telekom-header/telekom-header.css
fix https://github.com/telekom/scale/issues/2130
=> fix: prevent flicker

packages/components/src/components/data-grid/cell-handlers/link-cell.tsx
This is intended to address the feature request #2255
The old behavior as well as the new behavior are tested.
E.g. the following two scale data grid columns are defined:
```javascript
{
type: 'link',
label: 'Produkt',
},
{
type: 'link',
label: 'Edition',
}
```
And now we can add the rows like this:
```javascript
data.push(
`https://products.telekom.de/?productId=${product.id}`,
{text: edition.name, href:`?productId=${product.id}`}
)
```
Which then looks like this:
=> make link cell types customizable

packages/components/src/components/data-grid/data-grid.css, packages/components/src/components/data-grid/data-grid.tsx
The spacing in the heading block would break with a heading and the `hide-menu` prop enabled.
=> fix(data-grid): heading height with hidden menu

packages/components/src/components/dropdown-select/dropdown-select.tsx
Implement global state to track the active dropdown. Modify handleClick method to close any other open dropdown before opening the clicked one. This ensures that only one dropdown can be open at a time.
=> fix(dropdown-select): ensure single dropdown open at a time

packages/components/src/components/telekom/app-navigation-user-menu/app-navigation-user-menu.tsx, packages/components/src/components/telekom/telekom-profile-menu/readme.md, packages/components/src/components/telekom/telekom-profile-menu/telekom-profile-menu.tsx, packages/storybook-vue/stories/components/telekom-brand-header-navigation/TelekomBrandHeader.stories.mdx, packages/storybook-vue/stories/components/telekom-brand-header-navigation/telekom-brand-header.md, packages/storybook-vue/stories/components/telekom-brand-header-navigation/telekom-brand-header_de.md
This PR should fix 2 issues:
1. the profile menu's links & buttons could not be activated via keyboard (since default behaviour was surpressed, even if no clickHandler defined)
2. there was no way to set a custom clickHandler to the profile menu's logout button (even if the underlying component already had the feature that could be used)
=> fix(telekom-profile-menu): keyboard accessibility & optional logout handler

packages/components/src/components/data-grid/data-grid.tsx
This fix only resets the sort order when the fields change, which may disable the sorting behaviour or change the field order.
If the data changes and an active sort order is set then this resorts the data accordingly.
Fixes #2313
=> #2313 data grid sort order

.github/workflows/build-pr.yml
This PR attempts to fix the failing visual-test job in the workflow.  It first removes the unneccessary `ref` for the `actions/checkout@v3` as it tries to pull references that might not exist in addition based on the latest [Docker changes ](https://docs.docker.com/compose/migrate/) the `docker-compose` used by our `docker-chromium` dependency is removed from July 2023, and we need to provide a Symlink that calls the new `docker compose` v2.
=> ci: sets up docker compose alias for compatibility

packages/components/src/components/dropdown-select/dropdown-select.tsx
Fixes https://github.com/telekom/scale/issues/2327
Scrolling issue if operating with keyboard for dropdown-select component fixed. Seems to be the bug from previous refactor (element ref on wrong container)
=> dropdown scroll fixed

packages/components/src/components/chip/__snapshots__/chip.spec.ts.snap, packages/components/src/components/chip/chip.css, packages/components/src/components/chip/chip.tsx, packages/components/src/components/chip/readme.md, packages/components/src/html/chip.html
Fixes https://github.com/telekom/scale/issues/2328
Chip keyboard handling fixed
=> chip accessibility fix

packages/components/src/components/checkbox/checkbox.css, packages/components/src/components/switch/switch.css, packages/components/src/html/checkbox.html
Fixes https://github.com/telekom/scale/issues/2300
=> checkbox and switch css fixes for high contrast mode

packages/storybook-vue/stories/setup_and_info/ScaleAndAngular_de.md, packages/storybook-vue/stories/setup_and_info/ScaleAndAngular_en.md, packages/storybook-vue/stories/setup_and_info/ScaleAndReact_de.md, packages/storybook-vue/stories/setup_and_info/ScaleAndReact_en.md, packages/storybook-vue/stories/setup_and_info/ScaleAndVue_de.md, packages/storybook-vue/stories/setup_and_info/ScaleAndVue_en.md
Fixes https://github.com/telekom/scale/issues/2315
camelCase to kebab-case event naming info added
PS I've checked, it works as kebab-case for Angular and Vue, also for React both with .addEventListener and with wrappers.
=> event part in storybook fixed

packages/components/src/components/telekom/telekom-profile-menu/telekom-profile-menu.css, packages/components/src/components/telekom/telekom-profile-menu/telekom-profile-menu.tsx, packages/components/src/html/telekom-header-profile-menu.html
Fixes https://github.com/telekom/scale/issues/2331
Fixes https://github.com/telekom/scale/issues/2293
telekom-profile-menu component was failing in case userInfo is not provided. The check for empty prop is added.
UPD: no serviceLinks + hideLoginSettings case fixed.
UPD: lil css nesting fix for nav item inside profile menu added
@amir-ba we could discuss how css should be refactored for components having shadow: false. now looks like muddle which i'm afraid to touch
=> no userInfo for profile-menu 

packages/components/src/components/data-grid/cell-handlers/tags-cell.tsx, packages/components/src/html/data-grid.html, packages/storybook-vue/stories/components/data-grid/DataGrid.stories.mdx
Fixes https://github.com/telekom/scale/issues/2297.
Props size and type for tag cell in data-grid changed from hardcoded to dynamic. Description in storybook extended
=> tag cell in data-grid extended

packages/components/src/components/data-grid/cell-handlers/cell-interface.ts, packages/components/src/components/data-grid/data-grid.tsx, packages/components/src/html/data-grid.html, packages/storybook-vue/stories/components/data-grid/DataGrid.stories.mdx
Fixes https://github.com/telekom/scale/issues/2202
=> feat(data-grid): adds presort to grid

packages/components/src/components/button/button.tsx
The name and value used on the button element are not submitted as part of the form event as these are not cloned onto the temporary button used for submitting the form.
=> Fix: submit button does not add name or value to submit form event

packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
this should fix https://github.com/telekom/scale/issues/2251
=> fix(nav-item): hover underline on function slots

packages/components/stencil.config.ts
Fixes https://github.com/telekom/scale/issues/2302
This adds the vscode-elements.json description file to the build directory. So that VSCode can provide auto-complete and Intellisense based on it.
=> doc: adds VS code support for Scale customElements

packages/components/src/components/tab-header/readme.md, packages/components/src/components/tab-header/tab-header.tsx, packages/components/src/components/tab-nav/tab-nav.tsx, packages/components/src/html/tab-nav.html, packages/storybook-vue/stories/components/tab-navigation/ScaleTabNav.vue, packages/storybook-vue/stories/components/tab-navigation/TabHeader.vue, packages/storybook-vue/stories/components/tab-navigation/TabNav.stories.mdx
Fixes https://github.com/telekom/scale/issues/2282
- now if selected tab gots disabled, selection moves to first available tab
- example of preselected tab logic added to storybook
=> fix(tab-nav): fixes preselect logic in tabs with disabled attribute

packages/components/src/components/accordion/accordion.tsx
A collapsible can now be individually expanded, independent of its containing accordion.
The `expanded` prop is now only propagated, if it is set to true on the parent accordion. This allows the developer to individually select which collapsibles should start expanded instead of all or none.
This change works seamlessly with the `dependent` prop and does not introduce any breaking changes.
=> feat(accordion): allow collapsible to be individually expanded

packages/components/src/components/data-grid/cell-handlers/text-cell.tsx, packages/components/src/components/data-grid/data-grid.tsx, packages/components/src/components/data-grid/readme.md, packages/components/src/html/data-grid.html, packages/storybook-vue/stories/components/data-grid/DataGrid.stories.mdx
This PR introduces the following changes:
**Feature 1**: Added the `scale-selection` event to the data grid component. This event is triggered every time the selection list updates, providing better integration and control over row selection.
**Feature 2**: Enhanced the editable text cell properties in the data grid. Now, the text cell supports additional properties supported by the underlying `scale-text-field`, allowing for more customization and improved user experience.
**Documentation**: Updates to documentation storybook for the new event and the text cell config.
=> feat(data-grid): add scale-selection event and enhance editable text field

packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css, packages/components/src/html/telekom-header.html
Fixes https://github.com/telekom/scale/issues/2363
Css selector logic fixed, so nav item won't look active having active=false
=> active=false in nav-item fixed

packages/components/src/components/dropdown-select/dropdown-select.tsx, packages/components/src/html/dropdown-select.html
Fixes https://github.com/telekom/scale/issues/2360
Check for hiddenInput el added.
=> fix: hidden input in dropdown-select fixed

packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.tsx
This PR addresses an issue in the telekom-nav-item component, where an attempt to set the attribute on a child element could result in an error if the child element is null. The fix adds a null check for the child element before setting the role attribute
=> fix(nav-item): add null check for child element on load

packages/components/src/components/date-picker/date-picker.tsx
should fix this error (must happen on comp init, while props are coming befor DOM is ready):
in all other places in the component, where querySelector is used, this check for undefined exists, so I've added here as well
=> fix: check for querySelector value added

.github/workflows/build-pr.yml
the actions/cache v2 is deprecated, therefore the version is updated to 3 fix build pipelines
=> ci: bumps cache action to 3

packages/components/src/components/segment/segment.css
Fixed accessibility issue in segment buttons (#2080) by changing selected color to background magenta and foreground white. Also changed background color of disabled selected button.
=> fix(segmented-button): contrast ratio scale segmented button (#2080)

.github/workflows/build-pr.yml, .github/workflows/codeql-analysis.yml
This replaces the deprecated Ubuntu image for the GitHub action runners.
=> ci: Update build-pr.yml to fix deprecated base image

packages/components/src/components/telekom/telekom-mobile-menu-item/telekom-mobile-menu-item.css, packages/components/src/html/telekom/telekom_header.html
Bugfix: I fixed issue number #2379 
The telekom-mobile-menu-item was placed in the wrong position in the firefox browser.
I fixed the positioning to also work in the Firefox Browser by changing a css position-property.
=> fix(telekom-mobile-menu-item): fixed icon placing

packages/components/src/components/dropdown-select/dropdown-select.e2e.ts, packages/components/src/components/dropdown-select/dropdown-select.spec.ts, packages/components/src/components/helper-text/helper-text.spec.ts, packages/components/src/components/link/link.spec.ts, packages/components/src/components/notification/notification.spec.ts
The dev-build leads to errors and warnings of some few test files:
- dropdown-select.e2e.ts: components option not supported and needed any more
- dropdown-select.spec.ts: casting to HTMLElement is missing
- helper-text.spec.ts, link.spec.ts, notification.spec.ts: removal of unused code
=> fix: dev build causes ts errors

packages/components/src/components/data-grid/readme.md, packages/components/src/components/dropdown-select/dropdown-select.css, packages/components/src/components/dropdown-select/dropdown-select.tsx, packages/components/src/components/dropdown-select/readme.md, packages/components/src/html/dropdown-select.html, packages/storybook-vue/stories/components/dropdown-select/DropdownSelect.stories.mdx, packages/storybook-vue/stories/components/dropdown-select/ScaleDropdownSelect.vue
I added an optional feature to the dropdown-select component, which allows clearing the selected dropwdown element by klicking an 'x' icon.
=> feat(dropdown-select): add clear button to improve user experience

packages/components/src/components/data-grid/data-grid.css, packages/components/src/components/data-grid/data-grid.tsx
Fixing the issue with overflowing data-grid table header text when width of the column is reduced.
The sort indicator icons were moved out of the text element and removed their absolute positioning as well as it was never reset and thus the icons were not visible. This I discovered by accident, not sure if previous behaviour was intentional or not, but this seems to work better. 
New position of sort indicator icons is after the header text which also seems to work better as it reduces the move of the text when icon appears.
=> fix(data-grid): fix overflowing table header text when title space reduced

packages/components/src/components/data-grid/data-grid.css, packages/components/src/components/data-grid/data-grid.tsx
The issue appears when the last on scroll event effect to update the scroll position of the header doesn't happen. It appears as it will not render until the next redraw, sometimes keeping the header stuck over table values when using freeze-headers option and scrolling back to top.
Proposed solution removes the use of on scroll event and utilizes the `position: sticky` for the table header.
=> fix(data-grid): fix issue with table header overlapping the table body
