README.md

Add a step-by-step guide on how to get up and running locally

feature: add getting started section to readme

---

packages/generator-sketch/.gitignore
packages/generator-sketch/package.json
packages/generator-sketch/src/index.tsx

- add .gitignore
- cleanup before generating new artefacts 
- check if a sketch file exists before trying to remove it

add .gitignore and cleanup

---

packages/components-react/jest.config.js
packages/components-react/package.json
yarn.lock

fix: add react-dom to components-react

---

examples/boilerplate-angular/yarn.lock
examples/boilerplate-react/yarn.lock
examples/boilerplate-vue/package.json
examples/boilerplate-vue/yarn.lock
yarn.lock

Upgrade dependencies for main repo and boilerplates

fix: upgrade dependencies

---

packages/components/src/components.d.ts
packages/components/src/components/button/__snapshots__/button.spec.ts.snap
packages/components/src/components/button/button.css
packages/components/src/components/button/button.spec.ts
packages/components/src/components/button/button.tsx
packages/components/src/components/button/readme.md
packages/components/src/index.html

feature: add unit tests to button; 
add disabled functionality; 
generate docs; 
provide examples in index.html; 
add missing css & variable docs

feature: add unit tests to button

---

packages/components/src/components/card/__snapshots__/card.spec.ts.snap
packages/components/src/components/card/card.e2e.ts
packages/components/src/components/card/card.spec.ts
packages/components/src/components/card/card.tsx

create unit tests for card

---

packages/components/src/components/card/card.css
packages/components/src/components/card/card.tsx
packages/components/src/components/card/readme.md
packages/components/src/index.html

- check if slots are used before rendering the markup
- add header and footer styling
- add css var docs

feature: enhance header and footer

---

packages/components/src/components/card/__snapshots__/card.spec.ts.snap
packages/components/src/components/card/card.spec.ts

Add snapshot tests for checking if slot markup is rendered correctly

test: card slots

---

packages/components/package-lock.json
packages/components/package.json
yarn.lock

to run the tests please use `npm` instead of `yarn` now

fix: update stencil and jest; 

---

.circleci/config.yml

Disable until #108 is resolved

disable circle ci tests until resolved

---

.circleci/config.yml
packages/components/package.json

fixed test execution on ci server

---

packages/html-to-sketch/html2asketch/nodeToSketchLayers.ts
packages/html-to-sketch/html2asketch/nodeTreeToSketchGroup.ts

This PR tracks work to add support for :after, :before and other pseudo elements.

Pseudo-element support for html-to-sketch

---

.circleci/config.yml
lerna.json

fix: changes the allowed branch in lerna from development to master

ci: removes development branch and adds feat/* to the tests workflow

---

.circleci/config.yml

corrects the regular expression to get circleci to recognize feat branches

fix: corrects regular expression

---

README.md

new phrasing after text editing

open source information

---

LICENSE

Update LICENSE Text

---

.github/workflows/publish.yml
packages/components/src/components/data-grid/data-grid.tsx
packages/components/src/components/menu-flyout/menu-flyout.tsx
packages/components/src/components/modal/modal.tsx

* build(publish): enable caching
* fix(components): use private class fields

retry 3.0.0-beta.4

---

packages/components/package.json
packages/components/src/components/textarea/readme.md
packages/components/src/components/textarea/textarea.tsx
packages/storybook-vue/stories/3_components/text-area/ScaleTextArea.vue
packages/storybook-vue/stories/3_components/text-area/TextArea.stories.mdx
packages/storybook-vue/stories/3_components/text-field/ScaleTextField.vue
packages/storybook-vue/stories/3_components/text-field/TextField.stories.mdx

fix: add story for readonly attribute in text-field, also attribute/story for textarea

---

packages/components/src/components/data-grid/data-grid.tsx
packages/components/src/html/theming.html
packages/design-tokens/src/tokens.js
packages/storybook-vue/stories/3_components/data-grid/DataGrid.stories.mdx

fix: tokens for headings

---

packages/components/src/components/telekom/app-navigation-main-mobile/app-navigation-main-mobile.css

https://github.com/telekom/scale/issues/340

fix(app-navigation): remove leaky svg style

---

packages/components/src/components/sidebar-nav-item/__snapshots__/sidebar-nav-item.spec.ts.snap
packages/components/src/components/sidebar-nav-item/readme.md
packages/components/src/components/sidebar-nav-item/sidebar-nav-item.tsx

https://github.com/telekom/scale/issues/335

feat(sidebar-nav): make current prop work with boolean values

---

packages/design-tokens/src/tokens.js

fix(design-tokens): value for h5 line-height

---

examples/boilerplate-vue/package.json

https://github.com/telekom/scale/security/dependabot/examples/boilerplate-vue/package.json/serve/open

chore(boilerplate): remadiate vulnerable dep

---

packages/components/src/components/telekom/app-footer/__snapshots__/app-footer.spec.ts.snap
packages/components/src/components/telekom/app-footer/app-footer.tsx
packages/components/src/html/telekom/header.html

https://github.com/telekom/scale/issues/354

fix(footer): accept any icon

---

packages/components/src/components/telekom/app-header/app-header.tsx

https://github.com/telekom/scale/issues/362

fix(app-header): pass href to nav-main

---

packages/components/src/components/telekom/app-header/app-header.css

https://github.com/telekom/scale/issues/366

fix(app-header): remove list bullet point from portal name

---

packages/components/src/components/switch/readme.md
packages/components/src/components/switch/switch.tsx
packages/components/src/components/table/readme.md
packages/components/src/components/table/table.tsx

add styles attributes to switch and table component

feat: add styles attributes

---

packages/components/src/components/slider/slider.css

in the near future we will have tokens for z-index values!

fix: z-index for slider thumb, it was clashing with the modal

---

packages/components/src/components/telekom/app-header/app-header.tsx

https://github.com/telekom/scale/issues/384

fix(app-header): use ID as visible mega-menu matcher

---

packages/components/src/components/collapsible/collapsible.tsx
packages/components/src/components/data-grid/data-grid.tsx
packages/components/src/components/rating-stars/rating-stars.spec.ts
packages/components/src/components/telekom/app-header/app-header.tsx
packages/components/src/components/telekom/app-navigation-main-mobile/app-navigation-main-mobile.tsx
packages/components/src/components/toast/toast.tsx
packages/components/src/utils/status-note.ts
packages/generator-sketch/src/diff-builds.js
packages/generator-sketch/src/index.js
packages/generator-sketch/src/inject.js
packages/html-to-sketch/html2asketch/helpers/background.ts
packages/html-to-sketch/html2asketch/nodeToSketchLayers.ts
packages/html-to-sketch/html2asketch/nodeTreeToSketchPage.ts

We couldn't fix a failing prettier check in https://github.com/telekom/scale/pull/444.
This fixes it.

fix: format

---

packages/components/src/components/telekom/app-footer/app-footer.tsx
packages/storybook-vue/stories/3_components/footer/AppFooter.vue
packages/storybook-vue/stories/3_components/footer/Footer.stories.mdx

https://github.com/telekom/scale/issues/422

feat(footer): enable custom slots

---

packages/components/src/components/checkbox/__snapshots__/checkbox.spec.ts.snap
packages/components/src/components/checkbox/checkbox.css
packages/components/src/components/checkbox/checkbox.tsx
packages/storybook-vue/stories/3_components/checkbox-group/CheckboxGroup.stories.mdx
packages/storybook-vue/stories/3_components/checkbox-group/ScaleCheckboxGroup.vue
packages/storybook-vue/stories/3_components/checkbox/Checkbox.stories.mdx
packages/storybook-vue/stories/3_components/checkbox/ScaleCheckbox.vue
packages/visual-tests/src/checkbox.visual.spec.js

fix: checkbox (and stories)

---

packages/components/package.json
packages/components/src/components/modal/modal.tsx
packages/components/src/html/modal.html
yarn.lock

https://github.com/telekom/scale/issues/549

fix(modal): init internal opened state with the Prop value

---

packages/components/src/components/telekom/app-header/app-header.css
packages/components/src/components/telekom/app-header/app-header.tsx

https://github.com/telekom/scale/issues/546

fix(app-header): change sticky class to follow BEM

---

packages/components/src/components/telekom/app-header/app-header.tsx
packages/components/src/components/telekom/app-mega-menu/app-mega-menu.tsx
packages/components/src/components/telekom/nav-icon/nav-icon.tsx
packages/components/src/components/telekom/nav-main/nav-main.tsx
packages/components/src/components/telekom/nav-segment/nav-segment.tsx
packages/storybook-vue/stories/3_components/brand-header/BrandHeader.stories.mdx

- add deprication notes to components
- adapt app-header, the steering component

refactor: add deprecation notes; adapt steering app-header

---

packages/components/src/components/modal/modal.tsx
packages/components/src/html/modal.html
packages/components/src/utils/utils.ts

Fixes a regression in https://github.com/telekom/scale/issues/428#issuecomment-960621109

fix(modal): closing is prevented with legacy event

---

packages/storybook-vue/stories/3_components/date-picker/DatePicker.stories.mdx

https://github.com/telekom/scale/issues/736

docs: improve datepicker usage example

---

packages/components/src/components/date-picker/date-picker.css

https://github.com/telekom/scale/issues/717

fix(date-picker): fix layout glitch when zoomed out

---

packages/components/src/components/notification-message/readme.md
packages/components/stencil.config.ts

Potentially, and hopefully fixes #659 
---
https://github.com/ionic-team/stencil/issues/1948 👀

fix: enable `extras.cloneNodeFix` config for Stencil

---

packages/components/src/components/sidebar-nav/__snapshots__/sidebar-nav.spec.ts.snap
packages/components/src/components/sidebar-nav/sidebar-nav.spec.ts
packages/components/src/components/sidebar-nav/sidebar-nav.tsx

https://github.com/telekom/scale/issues/764

fix(sidebar-nav): set initial collapsible state

---

packages/components/src/components/sidebar-nav-collapsible/sidebar-nav-collapsible.css
packages/components/src/components/sidebar-nav/sidebar-nav.css
packages/storybook-vue/stories/3_components/sidebar-navigation/SidebarNav.stories.mdx

https://github.com/telekom/scale/issues/838

fix(sidebar-nav-collapsible): proper opacity for chevron

---

packages/components/src/components/checkbox/checkbox.css
packages/components/src/global/whitelabel.css

https://github.com/telekom/scale/issues/892

fix(checkbox): show icon in neutral mode

---

packages/components/src/components/slider/__snapshots__/slider.spec.ts.snap
packages/components/src/components/slider/readme.md
packages/components/src/components/slider/slider.tsx
packages/storybook-vue/stories/3_components/slider/ScaleSlider.vue
packages/storybook-vue/stories/3_components/slider/Slider.stories.mdx

https://github.com/telekom/scale/issues/883

feat(slider): add name prop

---

packages/storybook-vue/.storybook/preview-head.html
packages/storybook-vue/stories/guidelines/Colors.stories.mdx
packages/storybook-vue/stories/guidelines/Typography.stories.mdx

Colors Color Table and Typography Color Table

Next colors

---

packages/components/src/components/pagination/pagination.spec.ts
packages/components/src/components/pagination/pagination.tsx
packages/components/src/components/pagination/readme.md

* fix: add a direction property to pagination events
* Fixes: #931

fix(pagination): add direction to pagination events (#931)

---

packages/components/src/components/checkbox/checkbox.css
packages/components/src/components/switch/switch.css

tried cleaning up the switch component a bit, pls let me know if it looks ok

Dark mode switch refactor

---

.github/workflows/publish.yml
package.json

and deprecate `@telekom/scale-design-tokens` in favor of the new `@telekom/design-tokens`

chore: `next` dist tag

---

packages/storybook-vue/stories/update_history/Development_de.md
packages/storybook-vue/stories/update_history/Development_en.md

docs: update history / code translation

---

packages/components/src/components/button/button.tsx
packages/components/src/components/button/readme.md
packages/storybook-vue/stories/components/button/Button.stories.mdx
packages/storybook-vue/stories/components/button/ScaleButton.vue

feat(button): add `name` and `value` props

---

packages/components/src/components/toggle-button/readme.md
packages/components/src/components/toggle-button/toggle-button.tsx

closes: https://github.com/telekom/scale/issues/658

feat: add setFocus method to toggle-button

---

packages/components/src/components/menu-flyout-list/menu-flyout-list.css

fixes https://github.com/telekom/scale/issues/1009

fix: increase flyout zindex

---

packages/components/src/components/telekom/app-header/app-header.css

https://github.com/telekom/scale/issues/990

fix: avoid hiding elements directly under scrolled header

---

packages/components/src/components/telekom/app-header/app-header.tsx
packages/components/src/html/telekom/header-custom.html
packages/storybook-vue/stories/components/brand-header-navigation/BrandHeader.stories.mdx

https://github.com/telekom/scale/issues/1068

fix(header): add logo-inverse slot

---

packages/components/src/components/telekom/app-footer/app-footer.css
packages/components/src/components/telekom/app-header/app-header.css
packages/components/src/components/telekom/logo/__snapshots__/logo.spec.ts.snap
packages/components/src/components/telekom/logo/logo.css
packages/components/src/components/telekom/logo/logo.tsx

https://github.com/telekom/scale/issues/1043

feat(logo): shadow parts and css variables

---

packages/components/src/components/tooltip/readme.md
packages/components/src/components/tooltip/tooltip.css
packages/components/src/components/tooltip/tooltip.tsx

https://github.com/telekom/scale/issues/837

feat(tooltip): shadow parts and css variables

---

README.md
packages/components/README.md
packages/design-tokens/README.md

```diff
-https://telekom.github.io/scale/?path=/story/scale-for-designers-getting-started--page
+https://telekom.github.io/scale/?path=/docs/setup-info-getting-started-for-designers--page
```

docs(readme): fix designer links

---

packages/components/src/components/modal/modal.tsx
packages/components/src/components/modal/readme.md
packages/storybook-vue/stories/components/modal/Modal.stories.mdx
packages/storybook-vue/stories/components/modal/ScaleModal.vue

fix(modal): remove customClass attribute leftover

---

packages/components/src/components/data-grid/cell-handlers/actions-cell.tsx
packages/components/src/html/data-grid.html

fix(data-grid): enable content width check for actions cell

---

packages/components/src/components/menu-flyout/menu-flyout.tsx

it's most likely a `this` problem but could not reproduce.
https://github.com/telekom/scale/issues/1096

fix(flyout): avoid type errors list

---

packages/components/src/components/modal/modal.css
packages/storybook-vue/stories/components/modal/Modal.stories.mdx

feat(modal): add --min-height-window var

---

packages/components/src/components/menu-flyout/menu-flyout.tsx

Fixes #922, ~~and also 1122!~~
@marvinLaubenstein please 👀

feat(menu-flyout): close menu with click on trigger

---

packages/components/src/components/button/button.css
packages/components/src/components/radio-button/radio-button.css
packages/components/src/components/toggle-button/toggle-button.css
packages/storybook-vue/stories/components/button/Button.stories.mdx
packages/storybook-vue/stories/components/radio-button/RadioButton.stories.mdx

@felix-ico somehow this was left out from the previous PR, please take a look (visual tests should be fine).

refactor: remove --telekom-color-ui-outlined-fill-disabled

---

packages/components/src/components/menu-flyout/menu-flyout.tsx
packages/components/src/html/flyout-menu.html
packages/storybook-vue/stories/components/flyout-menu/MenuFlyout.stories.mdx

fix(menu-flyout): properly close sublists

---

packages/storybook-vue/stories/update_history/Design_de.md
packages/storybook-vue/stories/update_history/Design_en.md

refactor(storybook): target blanks

---

packages/components/src/components/link/link.css

fix(link): use currentColor when inside Tooltip (a11y)

---

packages/components/src/components/dropdown-select-item/dropdown-select-item.tsx

Fixes #1194
@nowseemee please take a look 🙏

fix(dropdown-select-item): reflect `value` prop

---

packages/components/src/components/data-grid/readme.md
packages/components/src/components/switch/__snapshots__/switch.spec.ts.snap
packages/components/src/components/switch/readme.md
packages/components/src/components/switch/switch.css
packages/components/src/components/switch/switch.tsx
packages/components/src/html/switch.html
packages/storybook-vue/stories/components/switch/switch.stories.mdx
packages/visual-tests/src/switch.visual.spec.js

refactor(switch): mobile 📱

---

packages/components/src/components/switch/switch.css
packages/components/src/html/slider.html
packages/visual-tests/src/switch.visual.spec.js

https://github.com/telekom/scale/pull/1224

fix: switch thumb

---

packages/components/src/components/checkbox/checkbox.tsx

fix(checkbox): rename private class property to avoid clashing with restricted name

---

packages/components/src/components/callout/callout.css

fix(callout): 🥚

---

packages/components/src/components/slider/slider.css

to match the latest update for the Switch (#1244)
~~@nowseemee please~~ 👀

fix(slider): thumb shadow

---

packages/components/src/components/checkbox/checkbox.css

fix(checkbox): box-sizing

---

packages/components/src/components/checkbox/checkbox.css

fix(checkbox): size when invalid

---

packages/storybook-vue/stories/guidelines/Colors.stories.mdx

feat: adding UI black and white
fix: solving problem with empty contrast arrays
Hi @nowseemee, the changes were checked visually. Could you approve it again from code side, so I can merge it ? 🙂

feat: adding UI black and white

---

packages/components/src/components/data-grid/data-grid.tsx

https://github.com/telekom/scale/issues/1268

fix: textAlign

---

packages/components/src/components/dropdown/dropdown.css

fixes https://github.com/telekom/scale/issues/1279

fix: handle prefers-color-scheme

---

packages/components/src/components/radio-button/radio-button.tsx

fix(radio-button): solving spacing clickability problem

---

packages/components/src/components/telekom/logo/__snapshots__/logo-svg.spec.ts.snap
packages/components/src/components/telekom/logo/__snapshots__/logo.spec.ts.snap
packages/components/src/components/telekom/logo/logo-svg.tsx
packages/components/src/components/telekom/logo/logo.tsx
packages/components/src/components/telekom/logo/readme.md
packages/components/src/components/telekom/telekom-app-name/readme.md
packages/components/src/components/telekom/telekom-app-name/telekom-app-name.css
packages/components/src/components/telekom/telekom-app-name/telekom-app-name.tsx
packages/components/src/components/telekom/telekom-header/readme.md
packages/components/src/components/telekom/telekom-header/telekom-header.css
packages/components/src/components/telekom/telekom-header/telekom-header.tsx
packages/components/src/html/telekom-header.html
packages/components/src/utils/utils.ts

feat(brand-bar): add new component

---

packages/storybook-vue/stories/setup_and_info/GettingStartedForDevelopers_en.md

fix(docs): lazy

---

packages/components/src/components/telekom/telekom-header/telekom-header.css
packages/components/src/components/telekom/telekom-nav-flyout/readme.md
packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.css
packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.tsx
packages/components/src/components/telekom/telekom-nav-item/readme.md
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.tsx
packages/components/src/components/telekom/telekom-nav-list/readme.md
packages/components/src/components/telekom/telekom-nav-list/telekom-nav-list.css
packages/components/src/components/telekom/telekom-nav-list/telekom-nav-list.tsx
packages/components/src/html/telekom-header.html

~~To discuss implementation details…~~
Featuring, new bare-bones:
Usage example in `telekom-header.html`…

feat(telekom-header): prototyping stuff

---

packages/components/package.json
packages/components/src/components/telekom/telekom-header/telekom-header.css
packages/components/src/components/telekom/telekom-header/telekom-header.tsx
packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.css
packages/components/src/components/telekom/telekom-nav-item/readme.md
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.tsx
packages/components/src/components/telekom/telekom-nav-list/readme.md
packages/components/src/components/telekom/telekom-nav-list/telekom-nav-list.css
packages/components/src/components/telekom/telekom-nav-list/telekom-nav-list.tsx
packages/components/src/global/custom-media.css
packages/components/src/html/telekom-header.html
packages/components/stencil-dev.config.ts
packages/components/stencil-staging.config.ts
packages/components/stencil.config.ts
yarn.lock

(All variants and breakpoints.)

feat(telekon-header): improve styles for list and item

---

packages/components/src/components/telekom/telekom-header/readme.md
packages/components/src/components/telekom/telekom-header/telekom-header.css
packages/components/src/components/telekom/telekom-header/telekom-header.tsx
packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.tsx
packages/components/src/components/telekom/telekom-nav-item/readme.md
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.tsx
packages/components/src/components/telekom/telekom-nav-list/readme.md
packages/components/src/components/telekom/telekom-nav-list/telekom-nav-list.css
packages/components/src/components/telekom/telekom-nav-list/telekom-nav-list.tsx
packages/components/src/html/telekom-header.html

feat(telekom-header): no shadow for `nav-list` and `nav-item`

---

packages/components/src/components/telekom/telekom-header/telekom-header.css
packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.css
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
packages/components/src/components/telekom/telekom-nav-list/telekom-nav-list.css
packages/components/src/html/telekom-header.html

…and other small adjustment based on feedback.

fix(telekom-header): adjust layout to match grid

---

packages/components/src/components/telekom/telekom-nav-flyout/readme.md
packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.tsx
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
packages/components/src/components/telekom/telekom-nav-list/telekom-nav-list.tsx

fix(telekom-header): flyout hover/click handling

---

packages/components/src/components/tooltip/tooltip.tsx
packages/storybook-vue/stories/components/tooltip/tooltip.md

https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/

refactor(tooltip): a11y 💙

---

packages/components/src/components/telekom/app-header/app-header.tsx

Fixes #873 
@nowseemee may you please take a look at this one, chef?

fix(app-header): esc key only when open, for user menu

---

packages/components/src/components/menu-flyout/menu-flyout.tsx
packages/components/src/components/telekom/app-header/app-header.tsx
packages/components/src/components/telekom/nav-icon/__snapshots__/nav-icon.spec.ts.snap
packages/components/src/components/telekom/nav-icon/nav-icon.tsx

fix(nav-icon): add role=button if no href

---

packages/components/src/components/button/button.css
packages/components/src/components/data-grid/cell-handlers/html-cell.tsx
packages/storybook-vue/stories/components/button/Button.stories.mdx
packages/storybook-vue/stories/components/data-grid/DataGrid.stories.mdx

@nowseemee sorry for the mention-bombing, this as well, please 🙏

fix(data-grid): details affecting buttons

---

packages/components/src/components/telekom/nav-main/__snapshots__/nav-main.spec.ts.snap
packages/components/src/components/telekom/nav-main/nav-main.tsx
packages/components/src/components/telekom/nav-main/readme.md

Small extension of #1592. Forgot one place for the link target 😅

feat: link targets in main navigation

---

packages/components/src/components/telekom/app-navigation-main-mobile/app-navigation-main-mobile.tsx

fix(app-navigation-main-mobile): second level if no children

---

packages/components/src/components/button/button.tsx
packages/components/src/components/tab-header/tab-header.tsx
packages/components/src/utils/utils.ts

Should fix #1587
@felix-ico please 👀

fix(tab-header): unsafe querySelector

---

packages/storybook-vue/stories/components/icon/Icon.stories.mdx

feat: adding section for selected icons from icon library

---

packages/components/src/components/notification-banner/notification-banner.css
packages/components/src/components/notification-message/notification-message.css
packages/components/src/components/notification-toast/notification-toast.css

- improve notification  high-contrast accessibility
- fix: #1571

feat: improving high-contrast mode accessibility

---

packages/components/src/components/data-grid/data-grid.tsx

fix: reset pagination to last page if new records are rendered are less than previous

---

packages/components/src/components/telekom/app-mega-menu/app-mega-menu.css

feat: adding high-contrast border due to better accessibility

---

packages/components/src/components/tag/tag.css
packages/storybook-vue/stories/components/tag/Tag.stories.mdx

Fix: #1450 
=> adding a possibility to implement user styles

refactor: adding a possibility to implement user styles

---

packages/storybook-vue/stories/FAQ_de.md
packages/storybook-vue/stories/FAQ_en.md

Removes a fact in the FAQ section that no longer holds true.

docs(faq): remove code-generated statement

---

packages/components/src/components/notification-banner/notification-banner.tsx
packages/components/src/components/notification-banner/readme.md
packages/components/src/components/notification-message/notification-message.tsx
packages/components/src/components/notification-message/readme.md
packages/components/src/components/notification-toast/__snapshots__/notificat-toast.spec.ts.snap
packages/components/src/components/notification-toast/notification-toast.tsx
packages/components/src/components/notification-toast/readme.md
packages/storybook-vue/stories/components/notification-banner/NotificationBanner.stories.mdx
packages/storybook-vue/stories/components/notification-banner/ScaleNotificationBanner.vue
packages/storybook-vue/stories/components/notification-message/NotificationMessage.stories.mdx
packages/storybook-vue/stories/components/notification-message/ScaleNotificationMessage.vue
packages/storybook-vue/stories/components/notification-toast/NotificationToast.stories.mdx
packages/storybook-vue/stories/components/notification-toast/ScaleNotificationToast.vue

feat: adding closeButtonLabel and -Title to notifications

---

examples/vitest/package.json
examples/vitest/test/button.test.ts
examples/vitest/test/dropdown-select.test.ts
examples/vitest/tsconfig.json
examples/vitest/vite.config.ts
examples/vitest/vitest.setup.ts

@felix-ico could you please take a look at this? 👻

docs: add vitest example

---

packages/components/src/components/telekom/logo/logo-svg.tsx
packages/components/src/components/telekom/logo/logo.tsx
packages/components/src/components/telekom/logo/readme.md
packages/components/src/components/telekom/telekom-footer-extended-navigation/readme.md
packages/components/src/components/telekom/telekom-header/readme.md
packages/components/src/components/telekom/telekom-header/telekom-header.tsx
packages/components/src/components/telekom/telekom-nav-item/readme.md
packages/storybook-vue/stories/components/beta-brand-header-navigation/BrandHeader.stories.mdx
packages/storybook-vue/stories/components/beta-brand-header-navigation/TelekomHeader.vue
packages/storybook-vue/stories/components/beta-brand-header-navigation/TelekomHeaderTemplate.vue

fix(telekom-header): allow link for logo

---

packages/components/src/components/telekom/telekom-header-data-back-compat/telekom-header-data-back-compat.tsx
packages/components/src/components/telekom/telekom-nav-flyout/readme.md
packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.css
packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.tsx
packages/components/src/components/telekom/telekom-nav-item/readme.md
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.tsx
packages/components/src/global/custom-media.css
packages/components/src/global/scale.css
packages/storybook-vue/stories/components/beta-brand-header-navigation/SlotFunctions.vue
packages/storybook-vue/stories/components/beta-brand-header-navigation/SlotFunctionsSlim.vue
packages/storybook-vue/stories/components/beta-brand-header-navigation/SlotFunctionsSubtle.vue
packages/storybook-vue/stories/components/beta-brand-header-navigation/SlotMobileDropdown.vue

fix(telekom-nav-flyout): add variant prop

---

examples/telekom-header-samples/data-api/index.html
packages/components/src/components/menu-flyout-list/readme.md
packages/components/src/components/menu-flyout/readme.md
packages/components/src/components/telekom/app-navigation-user-menu/app-navigation-user-menu.css
packages/components/src/components/telekom/app-navigation-user-menu/app-navigation-user-menu.tsx
packages/components/src/components/telekom/app-navigation-user-menu/readme.md
packages/components/src/components/telekom/telekom-header-data-back-compat/readme.md
packages/components/src/components/telekom/telekom-header-data-back-compat/telekom-header-data-back-compat.css
packages/components/src/components/telekom/telekom-header-data-back-compat/telekom-header-data-back-compat.tsx

@felix-ico could you take a look, please?

feat(header-back-compat): add support for userMenu

---

packages/components/src/components/notification-toast/notification-toast.css

set z-index 100 for toast notification

fix: resolve Telekom Brand Header is on top of toast messages

---

packages/components/src/components/notification-toast/notification-toast.css

fix text overlapping with icon in notification toast

fix: fix text overlapping issue in notification toast

---

packages/components/src/components/radio-button/radio-button.css
packages/components/src/components/radio-button/radio-button.tsx

space between disabled radio button and text should not be clickable

fix(radio-button): fix disabled radio button clickable issue

---

packages/components/src/components/loading-spinner/loading-spinner.tsx
packages/components/src/components/loading-spinner/readme.md
packages/storybook-vue/stories/components/loading-spinner/LoadingSpinner.stories.mdx
packages/storybook-vue/stories/components/loading-spinner/ScaleLoadingSpinner.vue

feat: adding accessibility title

---

packages/components/src/components/data-grid/cell-handlers/graph-cell.tsx

resolve floating point precision in grid cell

fix(grid-cell): resolve floating point precision issue

---

packages/visual-tests/src/pagination.visual.spec.js

~~Like I mention in the inline comment… 😄~~

fix(visual-tests): pagination buttons disabled

---

packages/components/src/components/checkbox/checkbox.tsx
packages/components/src/components/checkbox/readme.md
packages/storybook-vue/stories/components/checkbox/Checkbox.stories.mdx
packages/storybook-vue/stories/components/checkbox/ScaleCheckbox.vue

add required props in checkbox.

feat(checkbox): add required attribute

---

packages/components/src/components/dropdown/dropdown.css

fix: removing unneeded firefox css

---

packages/storybook-vue/stories/setup_and_info/ScaleAndReact_de.md
packages/storybook-vue/stories/setup_and_info/ScaleAndReact_en.md

https://github.com/telekom/scale/issues/1960

docs: add install script sample for scale-components-react

---

packages/components/src/components/notification/notification.tsx

https://github.com/telekom/scale/issues/2091

fix: set aria live on body part

---

packages/components/src/components/telekom/telekom-nav-item/readme.md
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.tsx

https://github.com/telekom/scale/issues/2004
https://github.com/telekom/scale/issues/2003

fix: set aria-current to false when changed

---

packages/components/src/components/dropdown-select/dropdown-select.tsx

https://github.com/telekom/scale/issues/1873

fix: ignore blur when inside a tab panel

---

packages/components/src/components/data-grid/cell-handlers/html-cell.tsx

https://github.com/telekom/scale/issues/2110

fix: set aria-label on nested button instead of scale-button

---

packages/components/src/components/switch/switch.css
packages/components/src/components/text-field/text-field.css
packages/components/src/components/text-field/text-field.tsx

https://github.com/telekom/scale/issues/2090
https://github.com/telekom/scale/issues/2081
https://github.com/telekom/scale/issues/2079
https://github.com/telekom/scale/issues/2078

fix: tk-network

---

packages/components/src/components/telekom/telekom-mobile-menu-item/telekom-mobile-menu-item.css

fix https://github.com/telekom/scale/issues/2096

fix: nav-item positioning

---

packages/components/src/components/telekom/app-header/app-header.tsx
packages/components/src/components/telekom/logo/logo.tsx
packages/components/src/html/telekom/header.html

fixes https://github.com/telekom/scale/issues/2102

fix: remove default language from logo to avoid deprecation warning

---

packages/components/src/global/fonts.css
packages/components/src/telekom/fonts/scale-fonts-telekom.css

fixes https://github.com/telekom/scale/issues/2118

fix: add font-display strategy for performance

---

.github/workflows/release.yml
packages/components-react/package.json
packages/components/package.json

feat: new gha workflow to create releases with bundled assets

---

packages/components/src/components/dropdown-select/dropdown-select.tsx

https://github.com/telekom/scale/issues/1873

fix: blur behavior

---

.github/workflows/publish.yml

Disables the cache for `yarn bootstrap`.

fix: CI publish

---

packages/components/src/components/tab-header/tab-header.tsx
packages/components/src/components/tab-nav/tab-nav.tsx

fix for https://github.com/telekom/scale/issues/2239

fix: handle setting disabled programaticcally

---

packages/components/src/components/telekom/telekom-mega-menu/telekom-mega-menu-column.css
packages/components/src/components/telekom/telekom-mega-menu/telekom-mega-menu.css

host-context doesn't work in ff and safari...

fix: mega menu grid

---

packages/components/src/components/telekom/telekom-header-data-back-compat/telekom-header-data-back-compat.tsx

fix https://github.com/telekom/scale/issues/2062

fix: add id to nav items

---

packages/components/src/components/telekom/telekom-header/telekom-header.css
packages/components/src/components/telekom/telekom-mobile-menu-item/telekom-mobile-menu-item.css
packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.tsx
packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
packages/components/src/components/telekom/telekom-nav-list/telekom-nav-list.css

this should fix https://github.com/telekom/scale/issues/2203

fix: focus outline on header bottom-bar

---

packages/components/src/components/table/table.tsx
packages/components/src/html/table-dynamic-cols.html

should fix https://github.com/telekom/scale/issues/2243

fix: allow sorting of dynamically added columns2

---

packages/components/src/components/telekom/telekom-nav-flyout/telekom-nav-flyout.tsx

this should fix https://github.com/telekom/scale/issues/2276

fix: listen for mouseleave on mega menu to close mega when moving cursor beyond mega menu

---

packages/components/src/components/dropdown-select/dropdown-select.tsx

fix(dropdown-select): remove type keyword in import

---

packages/storybook-vue/stories/Index_en.md

docs: update start page

---

packages/storybook-vue/stories/components/button/Button.stories.mdx

Fixes https://github.com/telekom/scale/issues/2312
Mistake in storybook fixed.

ghost btn in storybook 

---

packages/components/src/components/data-grid/cell-handlers/actions-cell.tsx
packages/components/src/components/data-grid/readme.md
packages/components/src/components/date-picker/date-picker.tsx

adds https://github.com/telekom/scale/issues/2236

feat(data-grid): added tooltip and scale-icon in data-grid action cell

---

packages/components/src/components/pagination/pagination.spec.ts
packages/components/src/components/pagination/pagination.tsx

fix: pagination with 0 elements

---

packages/components/src/components/telekom/telekom-mega-menu/telekom-mega-menu-column.css
packages/components/src/html/telekom/telekom_mega_menu_column.html

This fixes issue #2380 
fixed the positioning of the house icon, so that it is placed in the right position regardless of screen size

fix(mega-menu-column): fixed its positioning when screen is small
